### ISSUE TITLE
the method of cometspy.comets() can not working properly

### ISSUE THREAD

**Issue by wupeng1998** [segrelab/cometspy#15]
when i use cometspy to simulation, i find the method can not working properly.
here is my test code:
import cobra.test
    import cometspy as c
    from cometspy.utils import chemostat
    # make a model from a cobra model, open exchange reactions, and give a pop
    tb = cobra.test.create_test_model("textbook")
    m = c.model(tb)
    m.initial_pop = [0, 0, 1.e-4]
    m.open_exchanges()
    reservoir = {'glc__D_e': 0.01, 'nh4_e': 1000., 'pi_e': 1000.}
    c.layout, c.params = chemostat([m], reservoir, 0.1)
    c.params.set_param("maxCycles", 100)
    sim = c.comets(c.layout, c.params)
    sim.run()
    print(sim.total_biomass)

And there is the screenshot of my error.
![image](https://user-images.githubusercontent.com/57138506/164396585-2e6bf2ba-6144-4372-9e4c-96d7002ca3a7.png)

**Comment by jeremymchacon** [comment]
Hello, that means that the COMETS_HOME environmental variable was not found. It should have been set during COMETS installation (which is separate from and necessary to use cometspy, and can be downloaded at runComets.org) .

If you do have COMETS installed and for some reason the variable is not present in your python env, you can set it at the top of your script with the os package:

`import os
os.environ['COMETS_HOME'] = '/home/jeremy/comets/'`

where /home/jeremy/comets is where comets is on your system.
