### ISSUE TITLE
Change optimizer from Gurobi to GLPK

### ISSUE THREAD

**Issue by weeklymessage** [segrelab/cometspy#45]
Thank you for managing wonderful tools.

I have one question about changing optimizer.

In the nature protocol paper and documentation page (https://segrelab.github.io/cometspy/cometspy.html#cometspy-model-module), changing optimizer from Gurobi to GLPK seems to be possible, but I cannot find how to do this.

Could you update regarding documentation regarding to it?

Thanks.

**Comment by dukovski** [comment]
Thanks! Just a note, we'd like to retire glpk, and move on to glop from ORTools. Please be patient, I will release it in January. Unless you need it ASAP, in that case let me know and I can ship it to you. Cheers.

**Comment by weeklymessage** [comment]
Thank you @jeremymchacon and @dukovski for very rapid reply!! 

If you planed to replace open-source optimizer from GLPK to GLOP until Jan. , I can wait. Please take your time.

When the new version is released, it would be helpful if documentation include how to change optimizer and limitation of the tool's function under different optimizer, as @jeremymchacon metioned.

Thanks to your team for managing this wonderful tools again and I'm looking forward to the new version of cometspy in Jan.!!

p.s. @jeremymchacon I'm very happy for my username to give you fun haha

**Comment by weeklymessage** [comment]
Dear @jeremymchacon and @dukovski,
Thank you for managing valuable tool for scientific community.

I am waiting for release of COMETSpy with ORTools, instead of GLPK.
In previous, I was happy to hear that COMETSpy with ORTools would be released in Jan.

Can I get to know the release date or are there any ways to use it?

Thank you for managing wonderful tool again..! :)

**Comment by weeklymessage** [comment]
Thank you for your reply!
I will try :)

**Comment by zoey-rw** [comment]
@dukovski, I'd like to test Glop as a replacement for Gurobi! (because I sometimes get errors with the availability of Gurobi floating tokens. Hoping Glop will allow me to run processes simultaneously.)

After running:
```
SCRIPT=$1
VERSION=comets_glop
java -classpath /projectnb/cometsfba/comets_glop/or-tools/9.4.1874/ortools-java-9.4.1874-javadoc.jar:/projectnb/cometsfba/comets_glop/or-tools/9.4.1874/ortools-java-9.4.1874-sources.jar -Djava.library.path=/projectnb/cometsfba/or-tools/9.4.1874/:/projectnb/cometsfba/or-tools/9.4.1874: edu.bu.segrelab.comets.Comets -loader edu.bu.segrelab.comets.fba.FBACometsLoader -script $SCRIPT
```

I'm getting the following error:
`Error: Could not find or load main class edu.bu.segrelab.comets.Comets`

Do I need to install ortools-python? (I did, just in case). These are my environment variables:

```
JAVA_HOME=/share/pkg.7/java/12.0.1/install
#COMETS_HOME=/projectnb2/talbot-lab-data/zrwerbin/interactions/comets_2.10.5_linux
COMETS_HOME=/projectnb/cometsfba/comets_glop #Is this correct?
```
I assume the cometspy model.optimizer value will need to change as well?

**Comment by zoey-rw** [comment]
Hi @dukovski, do you have a timeline on pushing the Glop updates to cometspy?

**Comment by dukovski** [comment]
It should be working now, but I haven't tested it yet. I will take a look next week. What you tried above should work. The error is not about glop, but a wrong path to comets. let me take a look.
