### ISSUE TITLE
Error when reading a model.cmd

### ISSUE THREAD

**Issue by beacamara** [segrelab/cometspy#9]
Hi! I would like to report an error when I run this code for reading a model. Could you help me ?
I have included an screenshot of the code in my terminal.
Thank you so much

Beatriz

![Captura de pantalla de 2021-05-26 14-35-03](https://user-images.githubusercontent.com/11525843/119661068-36153800-be30-11eb-8fc5-93a6433728c1.png)

import cometspy as c            
path_to_model = "./iJO1366.cmd" # this must actually exist            
model = c.model()           
model.read_comets_model(path_to_model)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cometspy/model.py", line 597, in read_comets_model
    m_f_lines = [s for s in __read_file(path).splitlines() if s]
NameError: name '_model__read_file' is not defined

**Comment by jeremymchacon** [comment]
Thanks! We found the problem, there is a mangling of double-underscores which seems to be causing issues on some operating systems. Right now @djbajic is uploading a fix. If you don't want to wait, you can edit the model.py file directly and change the double-underscores in __read_file to single underscores.

**Comment by djbajic** [comment]
All set, thanks @beacamara for spotting the issue. It is fixed now, you can upgrade your cometspy using `pip install cometspy --upgrade`.

**Comment by beacamara** [comment]
Thank you so much.

**Comment by beacamara** [comment]
Hi again! I would like to report this error also in the script layout.py, lines 330 and 1429

File "/media/Backup/disk1/bcamara/portatil_acer/CNB_globachem/software/FLYCOP/FLYCOP-master/Scripts/ecoliLongTermFLYCOP.py", line 69, in initialize_layout
    layout=c.layout(file)
  File "/usr/local/lib/python3.8/dist-packages/cometspy/layout.py", line 132, in __init__
    self.read_comets_layout(input_obj)
  File "/usr/local/lib/python3.8/dist-packages/cometspy/layout.py", line 330, in read_comets_layout
    f_lines = [s for s in __read_file(input_obj).splitlines() if s]
NameError: name '_layout__read_file' is not defined
